def mostrar_menu_principal():
    print("========================================")
    print("       SISTEMA DE CONTROL ESCOLAR       ")
    print("========================================")
    print("  [ REGISTROS MAESTROS ]")
    print("  1. Gestión de Estudiantes")
    print("  2. Gestión de Profesores")
    print("  3. Gestión de Materias")
    print("  4. Gestión de Cursos")
    print("")
    print("  [ PROCESOS ACADÉMICOS ]")
    print("  5. Matriculación (Inscribir Alumno)")
    print("  6. Registro de Calificaciones")
    print("  7. Reporte Maestro (General)")
    print("  8. Salir del Sistema")
    print("========================================")